// frontend_new/src/routes/dashboard/calendar/+page.svelte
<script lang="ts">
	import { authStore } from '$lib/stores/auth';
	import { onMount } from 'svelte';
	import { goto } from '$app/navigation';
	import { 
		calendars, 
		calendarEvents, 
		isLoadingCalendars, 
		isLoadingEvents, 
		calendarError,
		calendarActions, 
		eventActions, 
		visibleCalendars, 
		visibleEvents 
	} from '$lib/stores/calendar';
	import CalendarHeader from '$lib/components/calendar/calendar-header.svelte';
	import CalendarGrid from '$lib/components/calendar/calendar-grid.svelte';
	import CalendarSidebar from '$lib/components/calendar/calendar-sidebar.svelte';
	import CalendarEventDialog from '$lib/components/calendar/calendar-event-dialog.svelte';
	import { getDaysOfWeek, getEventsInWeek } from '$lib/utils/calendar-helpers';
	import type { CalendarEvent, EventFormValues } from '$lib/types/calendar';

	let currentWeek = $state(getCurrentWeek());
	let selectedEvent = $state<CalendarEvent | null>(null);
	let isEventDialogOpen = $state(false);

	// Get current week starting Monday
	function getCurrentWeek() {
		const today = new Date();
		const day = today.getDay();
		const diff = today.getDate() - day + (day === 0 ? -6 : 1); // adjust when day is Sunday
		const monday = new Date(today);
		monday.setDate(diff);
		monday.setHours(0, 0, 0, 0);
		return monday;
	}

	// Derived values
	let daysOfWeek = $derived(getDaysOfWeek(currentWeek));
	let eventsInCurrentWeek = $derived(getEventsInWeek($visibleEvents, daysOfWeek[0]));

	onMount(async () => {
		console.log('🗓️ Calendar page mounting!');
		console.log('Auth store state:', $authStore);
		console.log('Calendar loading state:', $isLoadingCalendars);
		
		// Load calendar data if we have an encryption key
		// Auth checking is handled by the dashboard layout
		if ($authStore.encryptionKey) {
			console.log('Loading calendar data with encryption key...');
			await calendarActions.loadCalendars($authStore.encryptionKey);
			await eventActions.loadEvents($authStore.encryptionKey);
		} else {
			console.log('No encryption key available, skipping calendar data load');
		}
	});

	function openNewEventDialog(day?: Date, isAllDay = false) {
		selectedEvent = null;
		isEventDialogOpen = true;
	}

	function openEditDialog(event: CalendarEvent) {
		selectedEvent = event;
		isEventDialogOpen = true;
	}

	function closeEventDialog() {
		selectedEvent = null;
		isEventDialogOpen = false;
	}

	async function handleEventSubmit(values: EventFormValues) {
		if (!$authStore.encryptionKey) return;

		const eventData = {
			title: values.title,
			description: values.description,
			location: values.location,
			startTime: new Date(`${values.startDate}T${values.startTime}`),
			endTime: new Date(`${values.endDate}T${values.endTime}`),
			isAllDay: values.isAllDay,
			calendarId: values.calendarId,
			recurrencePattern: values.recurrenceFrequency && values.recurrenceFrequency !== 'none' ? {
				frequency: values.recurrenceFrequency,
				endDate: values.recurrenceEndDate ? new Date(values.recurrenceEndDate) : undefined,
				interval: values.recurrenceInterval || 1,
				daysOfWeek: values.daysOfWeek
			} : undefined
		};

		if (values.id) {
			// Update existing event
			await eventActions.updateEvent(values.id, eventData, $authStore.encryptionKey);
		} else {
			// Create new event
			await eventActions.createEvent(eventData, $authStore.encryptionKey);
		}
	}

	async function handleEventDelete(id: string) {
		await eventActions.deleteEvent(id);
	}

	async function handleCalendarCreate(name: string, color: string) {
		if (!$authStore.encryptionKey) return;
		await calendarActions.createCalendar(name, color, $authStore.encryptionKey);
	}

	async function handleCalendarEdit(id: string, name: string, color: string) {
		if (!$authStore.encryptionKey) return;
		await calendarActions.updateCalendar(id, name, color, $authStore.encryptionKey);
	}

	async function handleCalendarDelete(id: string) {
		await calendarActions.deleteCalendar(id);
	}

	function handleCalendarToggle(id: string, isVisible: boolean) {
		calendarActions.toggleCalendarVisibility(id, isVisible);
	}

	function handleSetDefaultCalendar(id: string) {
		// TODO: Implement set default calendar
		console.log('Set default calendar:', id);
	}

	function handleEventUpdate(event: CalendarEvent) {
		// TODO: Implement drag and drop event updates
		console.log('Update event:', event);
	}
</script>

<svelte:head>
	<title>Calendar - Streamline Scheduler</title>
</svelte:head>

<!-- Full-screen calendar app -->
<div class="min-h-screen bg-gray-50">
	<!-- Top Navigation Bar -->
	<nav class="bg-white shadow-sm border-b border-gray-200">
		<div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
			<div class="flex justify-between h-16">
				<div class="flex items-center">
					<a href="/" class="flex-shrink-0 flex items-center">
						<h1 class="text-xl font-bold text-gray-900">Streamline Scheduler</h1>
					</a>
					<div class="ml-10 flex items-center space-x-8">
						<a href="/dashboard/can-do-list" class="text-gray-500 hover:text-gray-700 px-3 py-2 rounded-md text-sm font-medium">
							Can-Do List
						</a>
						<a href="/dashboard/calendar" class="bg-indigo-100 text-indigo-700 px-3 py-2 rounded-md text-sm font-medium">
							Calendar
						</a>
						<a href="/dashboard/scheduler" class="text-gray-500 hover:text-gray-700 px-3 py-2 rounded-md text-sm font-medium">
							Scheduler
						</a>
						<a href="/dashboard/settings" class="text-gray-500 hover:text-gray-700 px-3 py-2 rounded-md text-sm font-medium">
							Settings
						</a>
					</div>
				</div>
				<div class="flex items-center">
					<button 
						onclick={() => { authStore.signOut(); goto('/'); }}
						class="text-gray-500 hover:text-gray-700 px-3 py-2 rounded-md text-sm font-medium"
					>
						Sign Out
					</button>
				</div>
			</div>
		</div>
	</nav>

	<!-- Calendar Content -->
	{#if $isLoadingCalendars}
		<div class="flex h-screen items-center justify-center">
			<div class="text-center">
				<div class="animate-spin rounded-full h-32 w-32 border-b-2 border-indigo-600 mx-auto mb-4"></div>
				<p class="text-gray-600">Loading calendar...</p>
			</div>
		</div>
	{:else}
		<div class="flex h-screen">
			<!-- Calendar Sidebar -->
			<div class="w-80 bg-white border-r border-gray-200 flex-shrink-0 overflow-y-auto">
				<CalendarSidebar
					calendars={$calendars}
					onCalendarToggle={handleCalendarToggle}
					onCalendarCreate={handleCalendarCreate}
					onCalendarEdit={handleCalendarEdit}
					onCalendarDelete={handleCalendarDelete}
					onSetDefaultCalendar={handleSetDefaultCalendar}
				/>
			</div>
			
			<!-- Main Calendar Content -->
			<div class="flex-1 flex flex-col overflow-hidden">
				<!-- Calendar Header -->
				<div class="px-6 py-4 bg-white border-b border-gray-200">
					<CalendarHeader 
						currentWeek={currentWeek}
						setCurrentWeek={(week) => currentWeek = week}
						openNewEventDialog={openNewEventDialog}
					/>
				</div>
					
				{#if $calendarError}
					<div class="mx-6 mt-4 bg-red-50 border border-red-200 text-red-700 p-3 rounded-md">
						{$calendarError}
					</div>
				{/if}
				
				<!-- Calendar Grid -->
				<div class="flex-1 px-6 py-4 overflow-y-auto bg-gray-50">
					{#if $isLoadingEvents}
						<div class="text-center py-8">Loading your encrypted calendar...</div>
					{:else}
						<CalendarGrid 
							days={daysOfWeek}
							events={eventsInCurrentWeek}
							calendars={$visibleCalendars}
							openEditDialog={openEditDialog}
							openNewEventDialog={openNewEventDialog}
							onEventUpdate={handleEventUpdate}
						/>
					{/if}
				</div>
			</div>

			<!-- Event Dialog -->
			<CalendarEventDialog
				isOpen={isEventDialogOpen}
				selectedEvent={selectedEvent}
				calendars={$visibleCalendars}
				defaultCalendarId={$calendars.find(cal => cal.isDefault)?.id}
				onSubmit={handleEventSubmit}
				onDelete={handleEventDelete}
				onClose={closeEventDialog}
			/>
		</div>
	{/if}
</div>

// frontend/app/dashboard/calendar/page.tsx
'use client';

import { useEffect, useState, useMemo } from 'react';
import Link from 'next/link';
import { Button } from '@/components/ui/button';

import { CalendarHeader } from '@/components/dashboard/calendar-header';
import { CalendarGrid } from '@/components/dashboard/calendar-grid';
import { CalendarEventDialog, EventFormValues } from '@/components/dashboard/calendar-event-dialog';
import { CalendarSidebar } from '@/components/dashboard/calendar/calendar-sidebar';

import { CalendarEvent } from '@/utils/types';
import { useEncryptionKey } from '@/utils/hooks';

// Import our custom hooks
import { useCalendars } from './hooks/useCalendars';
import { useCalendarEvents } from './hooks/useCalendarEvents';
import { useCalendarSubscriptions } from './hooks/useCalendarSubscriptions';
import { getDaysOfWeek, getEventsInWeek } from './utils/calendarHelpers';

export default function CalendarPage() {
  const { encryptionKey, isLoading: isLoadingKey } = useEncryptionKey();
  const [currentWeek, setCurrentWeek] = useState<Date>(new Date());
  const [isDialogOpen, setIsDialogOpen] = useState<boolean>(false);
  const [selectedEvent, setSelectedEvent] = useState<CalendarEvent | null>(null);
  
  // Use our custom hooks
  const { 
    calendars, 
    error: calendarError, 
    setError, 
    handleCalendarToggle, 
    handleCalendarCreate, 
    handleCalendarEdit, 
    handleCalendarDelete,
    setCalendarAsDefault,
    loadCalendarsAndSetState
  } = useCalendars(encryptionKey);
  
  const {
    events,
    isLoading: isLoadingEvents,
    error: eventError,
    loadEvents,
    handleSubmitEvent,
    handleDeleteEvent,
    handleEventUpdate,
    moveEventToCalendar
  } = useCalendarEvents(encryptionKey, calendars);

  // Calculate derived data using useMemo to avoid unnecessary recalculations
  const daysOfWeek = useMemo(() => 
    getDaysOfWeek(currentWeek), [currentWeek]
  );
  
  const eventsInCurrentWeek = useMemo(() => 
    getEventsInWeek(events, daysOfWeek[0]), [events, daysOfWeek]
  );
  
  // Load data when encryption key is available
  useEffect(() => {
    const loadData = async () => {
      if (encryptionKey) {
        try {
          // First load calendars
          await loadCalendarsAndSetState(encryptionKey);
          // Then load events
          await loadEvents(encryptionKey);
        } catch (error) {
          console.error('Error loading calendar data:', error);
          setError('Failed to load calendar data');
        }
      }
    };
    
    loadData();
  }, [encryptionKey]);

  // Subscribe to real-time updates
  useCalendarSubscriptions(
    encryptionKey,
    async () => {
      if (encryptionKey) {
        await loadCalendarsAndSetState(encryptionKey);
      }
    },
    async () => {
      if (encryptionKey) {
        await loadEvents(encryptionKey);
      }
    }
  );
  
  // Function to handle calendar deletion with event moving
  const handleCalendarDeleteWithEvents = async (calendarId: string) => {
    try {
      // Delete the calendar and get the target calendar ID for moving events
      const targetCalendarId = await handleCalendarDelete(calendarId, moveEventToCalendar);
      
      if (targetCalendarId) {
        // Move all events from this calendar to the target calendar
        const eventsToMove = events.filter(event => event.calendarId === calendarId);
        for (const event of eventsToMove) {
          await moveEventToCalendar(event.id, targetCalendarId);
        }
      }
    } catch (error) {
      console.error('Error in handleCalendarDeleteWithEvents:', error);
      setError('Failed to delete calendar and move events');
    }
  };

  // Open dialog for editing an event
  const openEditDialog = (event: CalendarEvent) => {
    setSelectedEvent(event);
    setIsDialogOpen(true);
  };

  // Open dialog for creating a new event
  const openNewEventDialog = (day?: Date, calendarId?: string) => {
    setSelectedEvent(null);
    
    // If a day is provided, set the start time to the clicked time
    if (day) {
      const startTime = new Date(day);
      
      // Set end time to be 1 hour after start time
      const endTime = new Date(startTime);
      endTime.setHours(endTime.getHours() + 1);
      
      // Create a temporary "dummy" event to pass to the form
      const dummyEvent: CalendarEvent = {
        id: 'new', // This ID will never be used, it's just for the temporary object
        title: '',
        description: '',
        calendarId: calendarId ?? (calendars.find(c => c.isDefault)?.id ?? (calendars.length > 0 ? calendars[0].id : '')),
        startTime: startTime,
        endTime: endTime,
        createdAt: new Date()
      };
      
      // Set as selected event to prefill the form with these times
      setSelectedEvent(dummyEvent);
    }
    
    setIsDialogOpen(true);
  };

  // Handle submit event and close dialog
  const onSubmitEvent = async (values: EventFormValues) => {
    const success = await handleSubmitEvent(values);
    if (success) {
      setSelectedEvent(null);
      setIsDialogOpen(false);
    }
  };

  // Handle delete event and close dialog
  const onDeleteEvent = async (id: string) => {
    const success = await handleDeleteEvent(id);
    if (success && selectedEvent?.id === id) {
      setSelectedEvent(null);
      setIsDialogOpen(false);
    }
  };

  // Combine errors
  const error = calendarError ?? eventError;
  
  // Show loading or auth required message
  if (isLoadingKey) {
    return <div className="text-center py-8">Loading...</div>;
  }

  if (!encryptionKey && !isLoadingKey) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[50vh] p-4">
        <h1 className="text-2xl font-bold mb-4">Authentication Required</h1>
        <p className="text-center mb-4">
          You need to log in first to access your encrypted Calendar.
        </p>
        <Link href="/sign-in">
          <Button>Sign In</Button>
        </Link>
      </div>
    );
  }

  return (
    <div className="flex w-full h-full">
      {/* Calendar Sidebar */}
      <CalendarSidebar
        calendars={calendars}
        onCalendarToggle={handleCalendarToggle}
        onCalendarCreate={handleCalendarCreate}
        onCalendarEdit={handleCalendarEdit}
        onCalendarDelete={handleCalendarDeleteWithEvents}
        onSetDefaultCalendar={setCalendarAsDefault}
      />
      
      {/* Main Calendar Content */}
      <div className="flex-1 px-4">
        <CalendarHeader 
          currentWeek={currentWeek}
          setCurrentWeek={setCurrentWeek}
          openNewEventDialog={() => openNewEventDialog()}
        />
        
        {error && (
          <div className="bg-destructive/10 text-destructive p-3 rounded-md mb-4">
            {error}
          </div>
        )}
        
        {/* Display loading or calendar grid */}
        {isLoadingEvents ? (
          <div className="text-center py-8">Loading your encrypted calendar...</div>
        ) : (
            <CalendarGrid 
              days={daysOfWeek}
              events={eventsInCurrentWeek}
              calendars={calendars}
              openEditDialog={openEditDialog}
              openNewEventDialog={(day) => openNewEventDialog(day)}
              onEventUpdate={handleEventUpdate}
            />
        )}
        
        {/* Event dialog */}
        <CalendarEventDialog 
          isOpen={isDialogOpen}
          onOpenChange={setIsDialogOpen}
          selectedEvent={selectedEvent}
          calendars={calendars.filter(cal => cal.isVisible)}
          defaultCalendarId={calendars.find(cal => cal.isDefault)?.id}
          onSubmit={onSubmitEvent}
          onDelete={onDeleteEvent}
        />
      </div>
    </div>
  );
}
