// frontend/app/(auth-pages)/sign-in/page.tsx
'use client';

import { signInAction } from "@/app/actions";
import { FormMessage, Message } from "@/components/form-message";
import { SubmitButton } from "@/components/submit-button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { hashPassword, storeHashedPassword } from "@/utils/encryption";
import Link from "next/link";
import { useState } from "react";

export default function Login(props: { searchParams: Message }) {
  const searchParams = props.searchParams;
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    
    // Hash the password and store it in a cookie for client-side encryption
    const hashedPassword = hashPassword(password);
    storeHashedPassword(hashedPassword);
    
    // Create and submit the form data
    const formData = new FormData();
    formData.append('email', email);
    formData.append('password', password);
    
    await signInAction(formData);
  };

  return (
    <form className="flex-1 flex flex-col min-w-64" onSubmit={handleSubmit}>
      <h1 className="text-2xl font-medium">Sign in</h1>
      <p className="text-sm text-foreground">
        Don't have an account?{" "}
        <Link className="text-foreground font-medium underline" href="/sign-up">
          Sign up
        </Link>
      </p>
      <div className="flex flex-col gap-2 [&>input]:mb-3 mt-8">
        <Label htmlFor="email">Email</Label>
        <Input 
          name="email" 
          placeholder="you@example.com" 
          required 
          value={email}
          onChange={(e) => setEmail(e.target.value)}
        />
        <div className="flex justify-between items-center">
          <Label htmlFor="password">Password</Label>
          <Link
            className="text-xs text-foreground underline"
            href="/forgot-password"
          >
            Forgot Password?
          </Link>
        </div>
        <Input
          type="password"
          name="password"
          placeholder="Your password"
          required
          value={password}
          onChange={(e) => setPassword(e.target.value)}
        />
        <SubmitButton pendingText="Signing In...">
          Sign in
        </SubmitButton>
        <FormMessage message={searchParams} />
      </div>
    </form>
  );
}

// frontend_new/src/routes/auth/signin/+page.svelte
<script lang="ts">
	import { authStore } from '$lib/stores/auth';
	import { goto } from '$app/navigation';
	import { Button } from '$lib/components/ui/button';
	import { Input } from '$lib/components/ui/input';
	import { Label } from '$lib/components/ui/label';
	import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '$lib/components/ui/card';

	let email = '';
	let password = '';
	let isLoading = false;
	let error = '';

	async function handleSignIn() {
		if (!email || !password) {
			error = 'Please fill in all fields';
			return;
		}

		isLoading = true;
		error = '';

		try {
			// The auth store now handles deriving both auth hash and encryption key
			await authStore.signIn(email, password);
			goto('/dashboard');
		} catch (err) {
			error = err instanceof Error ? err.message : 'Sign in failed';
		} finally {
			isLoading = false;
		}
	}

	function handleKeyPress(event: KeyboardEvent) {
		if (event.key === 'Enter') {
			handleSignIn();
		}
	}
</script>

<svelte:head>
	<title>Sign In - Streamline Scheduler</title>
</svelte:head>

<div class="min-h-screen flex items-center justify-center bg-background py-12 px-4 sm:px-6 lg:px-8">
	<div class="flex-1 flex flex-col min-w-64 max-w-md">
		<h1 class="text-2xl font-medium">Sign in</h1>
		<p class="text-sm text-foreground">
			Don't have an account?{" "}
			<a class="text-foreground font-medium underline" href="/auth/signup">
				Sign up
			</a>
		</p>
		<form class="flex flex-col gap-4 mt-8" on:submit|preventDefault={handleSignIn}>
			<div>
				<Label for="email">Email</Label>
				<Input
					id="email"
					type="email"
					autocomplete="email"
					placeholder="you@example.com"
					bind:value={email}
					on:keypress={handleKeyPress}
					required
				/>
			</div>
			
			<div>
				<div class="flex justify-between items-center">
					<Label for="password">Password</Label>
					<a
						class="text-xs text-foreground underline"
						href="/auth/forgot-password"
					>
						Forgot Password?
					</a>
				</div>
				<Input
					id="password"
					type="password"
					autocomplete="current-password"
					placeholder="Your password"
					bind:value={password}
					on:keypress={handleKeyPress}
					required
				/>
			</div>

			{#if error}
				<div class="text-sm text-destructive bg-destructive/10 p-3 rounded-md">
					{error}
				</div>
			{/if}

			<Button type="submit" disabled={isLoading}>
				{isLoading ? 'Signing In...' : 'Sign in'}
			</Button>
		</form>
	</div>
</div>
