// frontend/app/(auth-pages)/sign-up/page.tsx
'use client';

import { signUpAction } from "@/app/actions";
import { FormMessage as AuthFormMessage, Message } from "@/components/auth/form-message";
import { SubmitButton } from "@/components/ui/submit-button";
import { Input } from "@/components/ui/input";
import Link from "next/link";
import { useState, useEffect, Suspense } from "react";
import { useSearchParams } from "next/navigation";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { zodResolver } from "@hookform/resolvers/zod";
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from "@/components/ui/form";
import { hashPasswordForAuth } from "@/utils/cryptography/encryption";

// Define the schema for form validation
const signUpSchema = z.object({
  email: z.string().email({ message: "Please enter a valid email address" }),
  password: z.string().min(6, { message: "Password must be at least 6 characters" }),
  confirmPassword: z.string().min(1, { message: "Please confirm your password" })
}).refine((data) => data.password === data.confirmPassword, {
  message: "Passwords don't match",
  path: ["confirmPassword"],
});

type SignUpFormValues = z.infer<typeof signUpSchema>;

function SignUpForm() {
  const searchParams = useSearchParams();
  const [message, setMessage] = useState<Message | null>(null);

  // Initialize react-hook-form with zod validation
  const form = useForm<SignUpFormValues>({
    resolver: zodResolver(signUpSchema),
    defaultValues: {
      email: '',
      password: '',
      confirmPassword: ''
    }
  });

  useEffect(() => {
    if (searchParams.has('success')) {
      setMessage({ success: searchParams.get('success')! });
    } else if (searchParams.has('error')) {
      setMessage({ error: searchParams.get('error')! });
    } else if (searchParams.has('message')) {
      setMessage({ message: searchParams.get('message')! });
    }
  }, [searchParams]);

  const onSubmit = async (values: SignUpFormValues) => {
    // Hash the password for authentication with Supabase
    const authHash = hashPasswordForAuth(values.password);
    
    const formData = new FormData();
    formData.append('email', values.email);
    formData.append('password', authHash);
    
    await signUpAction(formData);
  };

  return (
    <Form {...form}>
      <form 
        onSubmit={form.handleSubmit(onSubmit)} 
        className="flex flex-col min-w-64 max-w-64 mx-auto"
        autoComplete="on"
      >
        <h1 className="text-2xl font-medium">Sign up</h1>
        <p className="text-sm text text-foreground">
          Already have an account?{" "}
          <Link className="text-primary font-medium underline" href="/sign-in">
            Sign in
          </Link>
        </p>
        <div className="flex flex-col gap-4 mt-8">
          <FormField
            control={form.control}
            name="email"
            render={({ field }) => (
              <FormItem>
                <FormLabel htmlFor="signup-email">Email</FormLabel>
                <FormControl>
                  <Input 
                    id="signup-email"
                    type="email"
                    autoComplete="email"
                    placeholder="you@example.com" 
                    {...field} 
                  />
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />
          
          <FormField
            control={form.control}
            name="password"
            render={({ field }) => (
              <FormItem>
                <FormLabel htmlFor="new-password">Password</FormLabel>
                <FormControl>
                  <Input 
                    id="new-password"
                    type="password" 
                    autoComplete="new-password"
                    placeholder="Your password" 
                    {...field} 
                  />
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />

          <FormField
            control={form.control}
            name="confirmPassword"
            render={({ field }) => (
              <FormItem>
                <FormLabel htmlFor="confirm-password">Confirm Password</FormLabel>
                <FormControl>
                  <Input 
                    id="confirm-password"
                    type="password" 
                    autoComplete="new-password"
                    placeholder="Confirm your password" 
                    {...field} 
                  />
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />
          
          <SubmitButton pendingText="Signing up...">
            Sign up
          </SubmitButton>
          {message && <AuthFormMessage message={message} />}
        </div>
      </form>
    </Form>
  );
}

export default function Signup() {
  return (
    <Suspense fallback={<div>Loading...</div>}>
      <SignUpForm />
    </Suspense>
  );
}

// frontend_new/src/routes/auth/signup/+page.svelte
<script lang="ts">
	import { authStore } from '$lib/stores/auth';
	import { deriveAuthHash, deriveEncryptionKey } from '$lib/crypto/encryption';
	import { goto } from '$app/navigation';
	import { Button } from '$lib/components/ui/button';
	import { Input } from '$lib/components/ui/input';
	import { Label } from '$lib/components/ui/label';
	import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '$lib/components/ui/card';

	let email = '';
	let password = '';
	let confirmPassword = '';
	let isLoading = false;
	let error = '';

	async function handleSignUp() {
		if (!email || !password || !confirmPassword) {
			error = 'Please fill in all fields';
			return;
		}

		if (password !== confirmPassword) {
			error = 'Passwords do not match';
			return;
		}

		if (password.length < 8) {
			error = 'Password must be at least 8 characters long';
			return;
		}

		isLoading = true;
		error = '';

		try {
			// Derive authentication hash for server authentication
			const authHash = deriveAuthHash(password, email);
			
			// Derive encryption key for client-side data encryption
			const encryptionKey = deriveEncryptionKey(password, email);
			
			// Register with auth hash, then store encryption key locally
			await authStore.signUp(email, authHash, encryptionKey);
			goto('/dashboard');
		} catch (err) {
			error = err instanceof Error ? err.message : 'Sign up failed';
		} finally {
			isLoading = false;
		}
	}

	function handleKeyPress(event: KeyboardEvent) {
		if (event.key === 'Enter') {
			handleSignUp();
		}
	}
</script>

<svelte:head>
	<title>Sign Up - Streamline Scheduler</title>
</svelte:head>

<div class="min-h-screen flex items-center justify-center bg-background py-12 px-4 sm:px-6 lg:px-8">
	<div class="flex flex-col min-w-64 max-w-64 mx-auto">
		<h1 class="text-2xl font-medium">Sign up</h1>
		<p class="text-sm text-foreground">
			Already have an account?{" "}
			<a class="text-primary font-medium underline" href="/auth/signin">
				Sign in
			</a>
		</p>
		<form class="flex flex-col gap-4 mt-8" on:submit|preventDefault={handleSignUp}>
			<div>
				<Label for="signup-email">Email</Label>
				<Input
					id="signup-email"
					type="email"
					autocomplete="email"
					placeholder="you@example.com"
					bind:value={email}
					on:keypress={handleKeyPress}
					required
				/>
			</div>
			
			<div>
				<Label for="new-password">Password</Label>
				<Input
					id="new-password"
					type="password"
					autocomplete="new-password"
					placeholder="Your password"
					bind:value={password}
					on:keypress={handleKeyPress}
					required
				/>
			</div>

			<div>
				<Label for="confirm-password">Confirm Password</Label>
				<Input
					id="confirm-password"
					type="password"
					autocomplete="new-password"
					placeholder="Confirm your password"
					bind:value={confirmPassword}
					on:keypress={handleKeyPress}
					required
				/>
			</div>

			{#if error}
				<div class="text-sm text-destructive bg-destructive/10 p-3 rounded-md">
					{error}
				</div>
			{/if}

			<Button type="submit" disabled={isLoading}>
				{isLoading ? 'Signing up...' : 'Sign up'}
			</Button>
		</form>
	</div>
</div>
